import type { Metadata } from "next";
import { Bellefair,Barlow_Condensed,Barlow } from "next/font/google";
import "@/scss/main.scss";
import TestProvider from "@/providers/TestContext";


const bellfair = Bellefair({
  weight: ["400"],
  subsets: ["latin"],
});

export const barlow_condesed = Barlow_Condensed({
  weight:["400"],
  subsets:["latin"]
})

export const barlow= Barlow({
  weight:["400"],
  subsets:["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={bellfair.className}>
          <TestProvider>

          {children}

          </TestProvider>
          
          </body>

    </html>
  );
}
